Documentation changes.
pypa/flit pull request #666
Opened 2023-11-09 22:32 UTC by grandell1234

In this request I fixed a few grammatical errors and added in another way to install Flit using `pip3 install flit` instead of `python3 -m pip install flit`.

2023-11-10 10:15 UTC, Carreau approved these changes

2023-11-28 14:47 UTC, joukewitteveen requested changes
Apart from mentioning `pip3 install flit`, I think these changes are no good.

2023-11-28 14:47 UTC, joukewitteveen commented on README.rst
> +It tries to require less thought about packaging and helps you avoid common
"to require [...] and help" seems correct to me. "to require [...] and to help" is a bit redundant. The suggested "it tries to require [...] and [it] helps" can work, but I would not say it is better.

2023-11-28 14:47 UTC, joukewitteveen commented on README.rst
> +   You can edit this file to add other metadata, for example, to set up
I wouldn't add this comma since the example is setting up command line scripts, not the addition of other metadata.

2023-11-28 14:47 UTC, joukewitteveen commented on README.rst
> +a 'sdist' package, it will install and use Flit in a temporary environment.
You pronounce "sdist" starting with a consonant cluster? I would say S-dist, in which case "an" is the correct article. I don't know what the "official" pronunciation is.

2023-11-28 16:47 UTC, closed without merging